### ISSUE TITLE
Generated ruleset contains an invalid keyword

### ISSUE THREAD

**Issue by jeriedel24** [sektioneins/sng-tools#1]
When using snggen as of commit 44a77fc it generates a ruleset which contains amongst others the following lines:
```
## | --disable_xxe=y
## Disable XML External Entity (XXE)?
sp.disable_xxe.enable();
```

This leads to an error when running PHP 8.1.4 with snuffleupagus 192a24a (that is snuffleupagus 0.8.0-sng):
``PHP Fatal error:  [snuffleupagus][0.0.0.0][config][log] Unexpected keyword 'disable_xxe' on line 39 in Unknown on line 0``

The keyword 'disable_xxe' has been replaced by 'xxe_protection' in recent versions of snuffleupagus.
Furthermore it might be wise to add a condition:
```
@condition extension_loaded("xml");
sp.xxe_protection.enable();
@end_condition;
```

**Comment by bef** [comment]
fixed. thanks.
